services:
  - type: web
    name: webapp
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec rails server -p $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rails-db